version: 0.2

phases:
  pre_build:
    commands:
      - test -n "$AWS_ACCOUNT_ID"
      - test -n "$AWS_DEFAULT_REGION"
      - test -n "$ECR_REPOSITORY_URI"
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
  build:
    commands:
      - docker build --pull -t "$ECR_REPOSITORY_URI:$IMAGE_TAG" .
  post_build:
    commands:
      - docker push "$ECR_REPOSITORY_URI:$IMAGE_TAG"
      - aws ecr describe-images --repository-name "$ECR_REPOSITORY_NAME" --image-ids imageTag="$IMAGE_TAG"

